<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>displayList</name>
   <tag></tag>
   <elementGuidId>45b9ac9b-a3ca-4c8d-8908-d5676d2879ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.thehanger-icons-display-list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div[2]/div/div/header/div/div/div/span[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c340ebc4-d656-4540-b283-f6bba79c2b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thehanger-icons-display-list</value>
      <webElementGuid>6e9f8d3c-a8a0-4883-b3c1-08f15b7f5c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;small-12 large-9 columns&quot;]/div[@class=&quot;site-main-content-wrapper&quot;]/div[@class=&quot;shop_header_placeholder&quot;]/header[@class=&quot;woocommerce-archive-header&quot;]/div[@class=&quot;woocommerce-archive-header-inside&quot;]/div[@class=&quot;woocommerce-archive-header-tools site-secondary-font site-secondary-color&quot;]/div[@class=&quot;shop-tools&quot;]/span[@class=&quot;shop-display-list&quot;]/i[@class=&quot;thehanger-icons-display-list&quot;]</value>
      <webElementGuid>354f6665-834d-4dbb-827d-eaaad7456ec5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div[2]/div/div/header/div/div/div/span[2]/i</value>
      <webElementGuid>9c20ed07-c869-4972-bc5d-29c93c433f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/i</value>
      <webElementGuid>dfca6b9d-fecf-4459-acb2-1c1947f661c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
