<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputNoHP</name>
   <tag></tag>
   <elementGuidId>80669065-5def-49e4-b95a-389db06e29e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c1c9a1c-aebc-47a4-bde1-0a084d2a86c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>3d04c1e7-3d73-4964-a488-8c24decdc44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>eeaa1c8d-33c1-453d-9f1c-5d7ad95a5a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_phone</value>
      <webElementGuid>2add6d2f-efc0-45da-9286-f0e5ba800ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_phone</value>
      <webElementGuid>d272ea26-e1c1-44a4-8d8e-e8c4c1ba969d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>5e742933-2e91-4315-8f85-20cfc1e9a578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_phone&quot;)</value>
      <webElementGuid>fc367259-952d-45b3-8aba-e8a0cff081ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_phone']</value>
      <webElementGuid>7cb91fc8-0e4a-427a-a37c-1f52472b8cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_phone_field']/span/input</value>
      <webElementGuid>1f053478-fc47-463e-9548-fd2394598de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]/span/input</value>
      <webElementGuid>e040fed7-675c-4947-90c0-f88155431789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'billing_phone' and @id = 'billing_phone']</value>
      <webElementGuid>f848f43e-0739-4a44-a26e-6fc854c2b0c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
