<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonKembali</name>
   <tag></tag>
   <elementGuidId>091490c5-637a-4881-9265-6601221fcb13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>26ff34d3-ac9e-4e78-b946-d2efbffdf8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-cta btn-back flex justify-center sm:w-auto  w-full </value>
      <webElementGuid>58dfd284-acc1-4d1b-8996-d520bb7f9151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>26a02953-9fa8-47e1-9cd6-993d70c639db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kembali</value>
      <webElementGuid>65cf76d8-0907-4a42-b682-c03d6b8be097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[2]/div[@class=&quot;flex min-h-screen&quot;]/div[@class=&quot;pt-8 mx-32 w-3/5&quot;]/div[@class=&quot;mt-6&quot;]/div[@class=&quot;px-4 py-4 fixed bottom-0 left-0 z-10 sm:z-0 flex justify-center w-full bg-white border-t-thin border-gray-100 sm:relative sm:border-none sm:bg-transparent sm:w-auto sm:bottom-auto sm:top-auto sm:mt-8 sm:px-20&quot;]/button[@class=&quot;btn btn-cta btn-back flex justify-center sm:w-auto  w-full&quot;]</value>
      <webElementGuid>255dfa95-e0ad-4174-9b0b-51ab036bc394</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>a81a6380-51c5-4c28-b6c9-e82b0d6e4f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div[2]/div[3]/button</value>
      <webElementGuid>6fe6e9f2-def4-4853-a359-d314d7052f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='woocommerce-xendit-565'])[1]/preceding::button[1]</value>
      <webElementGuid>ff14a605-21b8-467e-afe5-d6ffb0529b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>3b11f32f-64b5-4cb1-949b-8314ead8fd53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Kembali' or . = 'Kembali')]</value>
      <webElementGuid>0580dce8-255a-4c61-8279-e70a945866e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
