<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputPaymentRadioBRI</name>
   <tag></tag>
   <elementGuidId>5b9560aa-767d-421b-bad3-6e732c592753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment_method_xendit_briva</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_method_xendit_briva']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c7014b7-3217-49f0-a86c-6e3fd0007218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_method_xendit_briva</value>
      <webElementGuid>f53af083-c9ce-4616-bc78-d034a899f230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>baad88eb-19f0-45bb-a4df-77fc1c1df326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>a4159eb8-632d-40db-a76b-53e2f72cfcdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>96de35af-4952-47be-899d-a54eb37d547e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>xendit_briva</value>
      <webElementGuid>ddd7ccb7-39bd-45b8-8b3a-62fdcce6d325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_method_xendit_briva&quot;)</value>
      <webElementGuid>47afda24-8e86-4c10-8e91-2086371befa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_method_xendit_briva']</value>
      <webElementGuid>25e33748-f797-4e44-b15c-9295080a93f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/ul/li[3]/input</value>
      <webElementGuid>a840eb11-340f-4fde-b124-b2730035dad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/input</value>
      <webElementGuid>806c4297-0115-4351-a79b-99181b063d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_method_xendit_briva' and @type = 'radio' and @name = 'payment_method']</value>
      <webElementGuid>b62cf42f-9d34-454a-be39-306088c5985e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
