<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verifyHalamanRingkasanPesanan</name>
   <tag></tag>
   <elementGuidId>5e5bfe92-ad71-4a9d-864f-90f080710fd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text-2xl.font-semibold.capitalize</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div[2]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>54973676-7390-4229-a149-c6171badca38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-2xl font-semibold capitalize</value>
      <webElementGuid>e0b65453-bba3-4f55-9277-3cccefb8fa71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ringkasan pesanan</value>
      <webElementGuid>9462d7d9-948a-4d66-9828-916a05768a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[2]/div[@class=&quot;flex min-h-screen&quot;]/div[@class=&quot;pt-8 px-16 w-2/5 bg-gray-100 bg-opacity-50 divide-y divide-gray-200 divide-solid&quot;]/div[@class=&quot;pb-2&quot;]/p[@class=&quot;text-2xl font-semibold capitalize&quot;]</value>
      <webElementGuid>d3d6406d-653e-489c-a894-8c75a4f53058</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/p</value>
      <webElementGuid>4344ab67-286d-4e49-bbda-455e065b1bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('7. Tekan ', '&quot;', 'Ya', '&quot;', ' jika sudah benar')])[1]/following::p[2]</value>
      <webElementGuid>33436925-ea46-438d-a183-155915c7dfd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='woocommerce-xendit-574'])[1]/preceding::p[1]</value>
      <webElementGuid>78a2461f-737d-428d-b536-51295ba1e382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ringkasan pesanan']/parent::*</value>
      <webElementGuid>d44cb35f-eb96-432e-b730-ef13cb5254fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>0a595347-aa1e-4efe-8eba-c0f8437909fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'ringkasan pesanan' or . = 'ringkasan pesanan')]</value>
      <webElementGuid>23982ea0-5f2f-4907-9250-2411616fe356</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
