<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonSubmitRegistrasi</name>
   <tag></tag>
   <elementGuidId>16ae30fe-5756-441f-a265-4aaffa2c2f88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#um-submit-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='um-submit-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66077294-26dd-4b0d-8eca-e18208e2dab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4a15e823-94b5-4d88-9d13-9b969dc0a16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>d34c6e10-4ec3-4b1e-94ff-13615f6a18d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-button</value>
      <webElementGuid>b423f1d4-ef7b-42f3-9711-e76db2ac79b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>um-submit-btn</value>
      <webElementGuid>327cb39c-628d-473f-bfb6-8f94ff2ea588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;um-submit-btn&quot;)</value>
      <webElementGuid>2ba84f13-e82a-403c-a550-eed9862d7e34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='um-submit-btn']</value>
      <webElementGuid>1bfe1ce7-baf5-4e47-bb2e-dfcd38abd3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-301']/div/figure/table/tbody/tr/td/div/div/form/div[2]/div/input</value>
      <webElementGuid>113ab00e-fc04-43e1-ba53-ac8644a3eca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>88d114dd-e3a1-419a-a7be-95114306282d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'um-submit-btn']</value>
      <webElementGuid>0cccba0a-4327-414d-b768-a7c4e9bc395e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
